// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAPKXLbaS4Ve_Xgmc5XZGs0O9U5d-JjDs',
    appId: '1:880936265935:web:1684222bd9f9eaefc42fba',
    messagingSenderId: '880936265935',
    projectId: 'newprg-1e6f6',
    authDomain: 'newprg-1e6f6.firebaseapp.com',
    storageBucket: 'newprg-1e6f6.firebasestorage.app',
    measurementId: 'G-X6RGLX3NLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmeJTXxMy2FtR3C071SUiDCimWldCmqIU',
    appId: '1:880936265935:android:4aac311cbb7ab090c42fba',
    messagingSenderId: '880936265935',
    projectId: 'newprg-1e6f6',
    storageBucket: 'newprg-1e6f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBha-QDMh4LTpPteTTzg6yZzN5ZPlyHGEQ',
    appId: '1:880936265935:ios:aa6d29dc0e5dad7dc42fba',
    messagingSenderId: '880936265935',
    projectId: 'newprg-1e6f6',
    storageBucket: 'newprg-1e6f6.firebasestorage.app',
    iosBundleId: 'com.jee.tha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBha-QDMh4LTpPteTTzg6yZzN5ZPlyHGEQ',
    appId: '1:880936265935:ios:1bba73ce0b71f180c42fba',
    messagingSenderId: '880936265935',
    projectId: 'newprg-1e6f6',
    storageBucket: 'newprg-1e6f6.firebasestorage.app',
    iosBundleId: 'com.example.instaForntpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAPKXLbaS4Ve_Xgmc5XZGs0O9U5d-JjDs',
    appId: '1:880936265935:web:7d68b34a05fa80f0c42fba',
    messagingSenderId: '880936265935',
    projectId: 'newprg-1e6f6',
    authDomain: 'newprg-1e6f6.firebaseapp.com',
    storageBucket: 'newprg-1e6f6.firebasestorage.app',
    measurementId: 'G-H1MJ7TY88Z',
  );
}
